# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmwave < Formula
  desc "HelmWave is like docker-compose for helm"
  homepage ""
  version "0.19.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.19.3/helmwave_0.19.3_darwin_amd64.tar.gz"
      sha256 "c2ded5673d17343b01ad7c53864d81bde1f184a8a49f751d95e3f6932f5c1444"

      def install
        bin.install "helmwave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helmwave/helmwave/releases/download/v0.19.3/helmwave_0.19.3_darwin_arm64.tar.gz"
      sha256 "6485d84b07771a975aca6d6640505835260140454d3322056249969300290114"

      def install
        bin.install "helmwave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmwave/helmwave/releases/download/v0.19.3/helmwave_0.19.3_linux_arm64.tar.gz"
      sha256 "e2a2ab3511d3050bbfeb55b35dcae026a872b59ac69914fbbe35eee890354dc0"

      def install
        bin.install "helmwave"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.19.3/helmwave_0.19.3_linux_amd64.tar.gz"
      sha256 "360c615c84941316b355a2fe508914c3142ca35ec9c1d3dda60c1bfef0dadae4"

      def install
        bin.install "helmwave"
      end
    end
  end
end
