# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmwave < Formula
  desc "HelmWave is like docker-compose for helm"
  homepage ""
  version "0.12.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.12.3/helmwave_0.12.3_darwin_amd64.tar.gz"
      sha256 "b9e975a81359d8604bfd4cde742cd47bf4d1f7b8dd1aa3459626804bf5b59c22"
    end
    if Hardware::CPU.arm?
      url "https://github.com/helmwave/helmwave/releases/download/v0.12.3/helmwave_0.12.3_darwin_arm64.tar.gz"
      sha256 "0af570aab698c834860cc3126f478a035da7a7071353cd73a5a4a5c774fd8d7f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.12.3/helmwave_0.12.3_linux_amd64.tar.gz"
      sha256 "75f11307bbf77db4259d4e2a47149a9c52e57a7d30c848811577b8c8ac420a2a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmwave/helmwave/releases/download/v0.12.3/helmwave_0.12.3_linux_arm64.tar.gz"
      sha256 "c42104fb5c4ec56abf0932d80d9088d9444e82322ed49a189583fb6abed1765b"
    end
  end

  def install
    bin.install "helmwave"
  end
end
