# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmwave < Formula
  desc "True release manager for Kubernetes"
  homepage "https://helmwave.app"
  version "0.36.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.36.2/helmwave_0.36.2_darwin_amd64.tar.gz"
      sha256 "2071ea833824d23826a8204f2578b8c8b519735b5d7f7e09a9d7ae1b1fa4a85a"

      def install
        bin.install "helmwave"
        generate_completions_from_executable(bin/"helmwave", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helmwave/helmwave/releases/download/v0.36.2/helmwave_0.36.2_darwin_arm64.tar.gz"
      sha256 "3fe082ac0470f3c60ed5e3e9df9f07a12d669b40e4ebd384eeb032002378e744"

      def install
        bin.install "helmwave"
        generate_completions_from_executable(bin/"helmwave", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.36.2/helmwave_0.36.2_linux_amd64.tar.gz"
      sha256 "af3d28517a5b508ce81a98c868229fb91df3efb51ce50899e96faa0ace6d33d6"

      def install
        bin.install "helmwave"
        generate_completions_from_executable(bin/"helmwave", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmwave/helmwave/releases/download/v0.36.2/helmwave_0.36.2_linux_arm64.tar.gz"
      sha256 "e69c8564dc0595c0c34f2dcb24090b99380b9a8686c5723b5ade97e7164ca19a"

      def install
        bin.install "helmwave"
        generate_completions_from_executable(bin/"helmwave", "completion", shells: [:bash, :zsh])
      end
    end
  end

  head "https://github.com/helmwave/helmwave.git", branch: "main"

  test do
    assert_match version.to_s, shell_output("#{bin/"helmwave"} --version")
  end
end
