# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmwave < Formula
  desc "HelmWave is like docker-compose for helm"
  homepage ""
  version "0.29.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.29.3/helmwave_0.29.3_darwin_amd64.tar.gz"
      sha256 "de9d1820f7925e5c5e53defdfecc9044293e1a0287e67f0f656918b84dd49c91"

      def install
        bin.install "helmwave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helmwave/helmwave/releases/download/v0.29.3/helmwave_0.29.3_darwin_arm64.tar.gz"
      sha256 "fd536f1d4f3446571737f49d176432474cf787d8c9c98fde5409cb2e8d7d7119"

      def install
        bin.install "helmwave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/helmwave/helmwave/releases/download/v0.29.3/helmwave_0.29.3_linux_amd64.tar.gz"
      sha256 "b755bb2fe7ef0ff3bd550ee8b9807e3c6f06aa656d24de046e94d8081621eecc"

      def install
        bin.install "helmwave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmwave/helmwave/releases/download/v0.29.3/helmwave_0.29.3_linux_arm64.tar.gz"
      sha256 "7b615dca72869c1c18f138880d587f4aaab843cf49400eb800c4ec836c20b6b5"

      def install
        bin.install "helmwave"
      end
    end
  end

  head "https://github.com/helmwave/helmwave.git", branch: "main"

  test do
    assert_match version.to_s, shell_output("#{bin}/helmwave --version")
  end
end
